'use server';
/**
 * @fileOverview This file implements a predictive query for the Predictive Behavior Audit.
 * It predicts the likely outcome of an intention based on historical behavioral patterns using local Ollama.
 */

import { z } from 'zod';
import { queryOllama, cleanAndParseJson, sanitizeNulls } from '@/ai/ollama';

const HistoricalLogSchema = z.object({
  title: z.string(),
  category: z.string(),
  effort: z.number(),
  completed: z.boolean(),
  friction: z.string().optional(),
  date: z.string(),
});

const PredictBehavioralOutcomeInputSchema = z.object({
  history: z.array(HistoricalLogSchema),
  currentIntention: z.object({
    title: z.string(),
    category: z.string(),
    effort: z.number(),
    scheduledTime: z.string(),
    date: z.string(),
  }),
});
export type PredictBehavioralOutcomeInput = z.infer<typeof PredictBehavioralOutcomeInputSchema>;

const PredictBehavioralOutcomeOutputSchema = z.object({
  prediction: z.enum(['completed', 'missed', 'partially_completed']),
  probability: z.number().describe('Confidence level from 0 to 1'),
  reasoning: z.string().describe('A brief explanation of why this outcome is predicted based on history.'),
  suggestedAction: z.string().describe('A small tweak to increase the chance of completion.'),
});
export type PredictBehavioralOutcomeOutput = z.infer<typeof PredictBehavioralOutcomeOutputSchema>;

function formatPredictPrompt(input: PredictBehavioralOutcomeInput): string {
  const historyText = input.history.map(h => 
    `- ${h.title} (${h.category}) | Effort: ${h.effort} | Result: ${h.completed ? 'Completed' : 'Missed'} | Notes: ${h.friction || ''}`
  ).join('\n');

  return `You are the "GapLogic Predictor", a behavioral science AI.
Analyze the user's historical performance to predict the outcome of their current intention.

### History (Past Intentions and Outcomes):
${historyText}

### Current Intention:
- Title: ${input.currentIntention.title}
- Category: ${input.currentIntention.category}
- Effort Level: ${input.currentIntention.effort}
- Scheduled Time: ${input.currentIntention.scheduledTime}
- Date: ${input.currentIntention.date}

### Task:
Predict if the user will actually complete this task. Identify patterns like "struggles with health on Mondays" or "overestimates work capacity when effort is > 4".
Be precise, empathetic, and diagnostic.

### Output format:
Return a JSON object with the following fields:
{
  "prediction": "completed" | "missed" | "partially_completed",
  "probability": <number between 0 and 1 representing confidence level>,
  "reasoning": "<string text>",
  "suggestedAction": "<string text>"
}
Do NOT return a JSON Schema wrapper (like "type", "properties", etc.). Just return the flat JSON object itself.`;
}

export async function predictBehavioralOutcome(input: PredictBehavioralOutcomeInput): Promise<PredictBehavioralOutcomeOutput> {
  const prompt = formatPredictPrompt(input);
  const text = await queryOllama(prompt, 'json');
  
  let parsed: any;
  try {
    parsed = cleanAndParseJson(text);
  } catch (e) {
    console.error("[predictBehavioralOutcome] JSON Parsing Failed. Raw text was:", text);
    throw new Error('Failed to parse Gemma output as JSON: ' + (e as Error).message);
  }

  // Normalize structure, keys, and values to match schema
  if (parsed && typeof parsed === 'object') {
    // Handle schema wrapper if generated by the model
    if ('properties' in parsed && typeof parsed.properties === 'object') {
      const props = parsed.properties;
      parsed = {
        prediction: props.prediction?.default ?? props.prediction,
        probability: props.probability?.default ?? props.probability,
        reasoning: props.reasoning?.default ?? props.reasoning,
        suggestedAction: props.suggestedAction?.default ?? props.suggestedAction ?? props.suggested_action?.default ?? props.suggested_action,
      };
    }

    // Coerce probability
    let prob = parsed.probability ?? parsed.confidence ?? parsed.prob;
    if (typeof prob === 'object') prob = 0.5;
    if (typeof prob === 'string') prob = parseFloat(prob) || 0.5;
    if (typeof prob !== 'number') prob = 0.5;

    // Coerce prediction
    let pred = parsed.prediction;
    if (pred !== 'completed' && pred !== 'missed' && pred !== 'partially_completed') {
      pred = 'completed'; // default fallback
    }

    parsed = {
      prediction: pred,
      probability: prob,
      reasoning: parsed.reasoning ?? parsed.explanation ?? parsed.reason ?? 'No detailed reasoning provided by local model.',
      suggestedAction: parsed.suggestedAction ?? parsed.suggested_action ?? parsed.suggestedTweak ?? parsed.suggested_tweak ?? 'Try breaking the task down into smaller steps.',
    };
  }

  parsed = sanitizeNulls(parsed);

  return PredictBehavioralOutcomeOutputSchema.parse(parsed);
}
